#:kivy 1.8.0

<Tile>:
    size: 100, 100
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'assets/tiles/Tiles/tileDirt.png'

<Row>:
    Tile:
        pos: root.x, root.y

    Tile:
        pos: root.x + root.tile_width, root.y

    Tile:
        pos: root.x + root.tile_width * 2, root.y


<Grid>:
    Row:
        pos: 50, 58
        tile_width: 100
    Row:
        pos: 0, 0
        tile_width: 100
